# Generated by Django 5.2.7 on 2025-10-25 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='assign',
        ),
    ]
